# MLMarker Training Datasets Filtering

This notebook loads the 183 PRIDE projects (PXDs) used to train the MLMarker model (from `SupplementaryTableS1.tsv`).

In [1]:
import os 
import pandas as pd

In [2]:
# PATH_MLMARKER = r"C:\Users\jung.arnaud\Project\HAMLET_MLMarker\mlmarker_pipeline\results_0909\run_meta_mlmarker_all_sample_nsaf_matrix.tsv"
PATH_MLMARKER = r"C:\Users\jung.arnaud\Project\HAMLET_MLMarker\mlmarker_pipeline\results_1109\run_meta_mlmarker_sample_nsaf_matrix.tsv"
PATH_TRAINING = r"C:\Users\jung.arnaud\Git_Folder\textmining\MLMarker\Training_PXDs\SupplementaryTableS1.tsv"
PATH_OUTPUT   = r"C:\Users\jung.arnaud\Project\HAMLET_MLMarker\mlmarker_pipeline\results_1109"

In [3]:
df_mlmarker = pd.read_csv(PATH_MLMARKER, sep='\t', header=0)
df_mlmarker

,pxd,run,source_parquet,tissue,confidence,tissue_2,confidence_2,tissue_3,confidence_3,tissue_4,confidence_4,tissue_5,confidence_5
0,PXD000013,VELOS02_01177,sample_nsaf_matrix.parquet,Bone marrow,0.1666,Spleen,0.0890,Lung,0.0883,Monocytes,0.0674,Testis,0.0627
1,PXD000013,VELOS02_01178,sample_nsaf_matrix.parquet,Bone marrow,0.1877,Spleen,0.1001,Lung,0.0794,Monocytes,0.0661,Testis,0.0599
2,PXD000013,VELOS02_01179,sample_nsaf_matrix.parquet,Bone marrow,0.1719,Spleen,0.0945,Lung,0.0841,Testis,0.0676,Monocytes,0.0668
3,PXD000013,VELOS02_01180,sample_nsaf_matrix.parquet,Bone marrow,0.1963,Spleen,0.0888,Lung,0.0793,Monocytes,0.0656,Testis,0.0611
4,PXD000013,VELOS02_01182,sample_nsaf_matrix.parquet,Bone marrow,0.1708,Spleen,0.0948,Lung,0.0867,Monocytes,0.0678,Testis,0.0652
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56617,PXD071075,/public/conode53/AIRFLOW/temp/PXD071075/diann/...,sample_nsaf_matrix.parquet,Bone marrow,0.1598,Lung,0.0823,Testis,0.0745,Kidney,0.0697,Monocytes,0.0615
56618,PXD071075,/public/conode53/AIRFLOW/temp/PXD071075/diann/...,sample_nsaf_matrix.parquet,Bone marrow,0.1524,Lung,0.0846,Testis,0.0808,Kidney,0.0687,Monocytes,0.0525
56619,PXD071075,/public/conode53/AIRFLOW/temp/PXD071075/diann/...,sample_nsaf_matrix.parquet,Bone marrow,0.1609,Lung,0.0966,Testis,0.0617,Monocytes,0.0584,Kidney,0.0533
56620,PXD071075,N.Proteotypic.Sequences,sample_nsaf_matrix.parquet,Testis,0.1302,Kidney,0.1069,Bone marrow,0.0995,Monocytes,0.0807,Lung,0.0719
56621,PXD071075,N.Sequences,sample_nsaf_matrix.parquet,Testis,0.1232,Kidney,0.1064,Monocytes,0.0859,Lung,0.0691,Bone marrow,0.0675

In [ ]:
with open(PATH_TRAINING, "r", encoding="utf-8") as f:
    training_pxds = [
        token for token in f.read().split() 
        if token.startswith("PXD") and token != "PXD_accession"
    ]
print(f"Total training PXDs loaded: {len(training_pxds)}")
print(f"First 10 PXDs: {training_pxds[:10]}")

df_training = pd.DataFrame(training_pxds, columns=["pxd"])
df_training

Total training PXDs loaded: 183
First 10 PXDs: ['PXD000072', 'PXD006517', 'PXD006776', 'PXD006863', 'PXD009258', 'PXD009393', 'PXD009261', 'PXD003534', 'PXD009118', 'PXD008205']

           pxd
0    PXD000072
1    PXD006517
2    PXD006776
3    PXD006863
4    PXD009258
..         ...
178  PXD008029
179  PXD008682
180  PXD002133
181  PXD007231
182  PXD013649

[183 rows x 1 columns]

In [5]:
# Example: filter an existing dataset (e.g., df_metadata) to exclude MLMarker training projects
df_unseen = df_mlmarker[~df_mlmarker["pxd"].isin(training_pxds)]
print(f"Kept {len(df_unseen)} unseen samples out of {len(df_mlmarker)}")

Kept 51027 unseen samples out of 56622

In [6]:
unseen_pxd = df_unseen['pxd'].unique()
unseen_pxd

array(['PXD000013', 'PXD000218', 'PXD000412', ..., 'PXD070477',
       'PXD071042', 'PXD071075'], dtype=object)

In [7]:
len(unseen_pxd)

1133

In [8]:
'filtered_'+os.path.basename(PATH_MLMARKER)

'filtered_run_meta_mlmarker_sample_nsaf_matrix.tsv'

In [9]:
df_unseen.to_csv(os.path.join(PATH_OUTPUT, 'filtered_'+os.path.basename(PATH_MLMARKER)), sep='\t', index=False)
print(f"File is located here: {os.path.join(PATH_OUTPUT, 'filtered_'+os.path.basename(PATH_MLMARKER))}")

File is located here: C:\Users\jung.arnaud\Project\HAMLET_MLMarker\mlmarker_pipeline\results_1109\filtered_run_meta_mlmarker_sample_nsaf_matrix.tsv