In [1]:
import pandas as pd
import requests
import os
from io import StringIO

In [2]:
pd.set_option('display.max_columns', None)

# Load the data

In [ ]:
dia_data_path = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\quant_data\diann_wide.parquet"
dda_data_path = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\quant_data\dnsaf_wide.parquet"

project_metadata_path = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\metadata.tsv"

In [4]:
dia_data = pd.read_parquet(dia_data_path)
dda_data = pd.read_parquet(dda_data_path)
project_metadata = pd.read_csv(project_metadata_path, sep="\t")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sander\\OneDrive\\Bureaublad\\Projects\\agentic-metadata\\quant_data\\diann_wide.parquet'

In [ ]:
dda_data.head()

         pxd     run  A0A024RBG1  A0A075B6H7  A0A075B6H8  A0A075B6H9  \
0  PXD068664  PURPL2         0.0         0.0         0.0         0.0
1  PXD068664     NT3         0.0         0.0         0.0         0.0
2  PXD068664     NT1         0.0         0.0         0.0         0.0
3  PXD068664     NT2         0.0         0.0         0.0         0.0
4  PXD068664  PURPL1         0.0         0.0         0.0         0.0

   A0A075B6I0  A0A075B6I1  A0A075B6I3  A0A075B6I4  A0A075B6I6  A0A075B6I7  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B6I9  A0A075B6J1  A0A075B6J2  A0A075B6J6  A0A075B6J9  A0A075B6K0  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B6K2  A0A075B6K4  A0A075B6K5  A0A075B6K6  A0A075B6L2  A0A075B6L6  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B6N1  A0A075B6N2  A0A075B6N3  A0A075B6N4  A0A075B6Q5  A0A075B6R0  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B6R2  A0A075B6R9  A0A075B6S0  A0A075B6S2  A0A075B6S4  A0A075B6S5  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B6S6  A0A075B6S9  A0A075B6T6  A0A075B6T7  A0A075B6T8  A0A075B6U4  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B6V5  A0A075B6W5  A0A075B6X5  A0A075B6Y3  A0A075B6Y9  A0A075B700  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A075B706  A0A075B759  A0A075B767  A0A087WSX0  A0A087WSY4  A0A087WSY6  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A087WSZ0  A0A087WSZ9  A0A087WT01  A0A087WT02  A0A087WT03  A0A087WTH1  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A087WTH5  A0A087WUL8  A0A087WV53  A0A087WV62  A0A087WVF3  A0A087WWA1  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A087WX78  A0A087WXM9  A0A087WXS9  A0A087X0K7  A0A087X0M5  A0A087X179  \
0         0.0         0.0         0.0         0.0     0.00000         0.0
1         0.0         0.0         0.0         0.0     0.00000         0.0
2         0.0         0.0         0.0         0.0     0.00296         0.0
3         0.0         0.0         0.0         0.0     0.00000         0.0
4         0.0         0.0         0.0         0.0     0.00000         0.0

   A0A087X1C5  A0A087X1G2  A0A096LNP1  A0A096LP01  A0A096LP49  A0A096LP55  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A096LPI5  A0A096LPK9  A0A0A0MRZ7  A0A0A0MRZ8  A0A0A0MRZ9  A0A0A0MS00  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0A0MS01  A0A0A0MS02  A0A0A0MS03  A0A0A0MS04  A0A0A0MS05  A0A0A0MS06  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0A0MS14  A0A0A0MS15  A0A0A0MT36  A0A0A0MT70  A0A0A0MT76  A0A0A0MT78  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0A0MT87  A0A0A0MT89  A0A0A0MT94  A0A0A0MTA4  A0A0A0MTA7  A0A0A6YYC5  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0A6YYD4  A0A0A6YYG2  A0A0A6YYG3  A0A0A6YYJ7  A0A0A6YYK1  A0A0A6YYK4  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0A6YYK6  A0A0A6YYK7  A0A0A6YYL3  A0A0B4J1U3  A0A0B4J1U4  A0A0B4J1U6  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J1U7  A0A0B4J1V0  A0A0B4J1V1  A0A0B4J1V2  A0A0B4J1V6  A0A0B4J1V7  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J1X5  A0A0B4J1X8  A0A0B4J1Y8  A0A0B4J1Y9  A0A0B4J1Z2  A0A0B4J200  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J234  A0A0B4J235  A0A0B4J237  A0A0B4J238  A0A0B4J240  A0A0B4J241  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J244  A0A0B4J245  A0A0B4J248  A0A0B4J249  A0A0B4J262  A0A0B4J263  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J264  A0A0B4J265  A0A0B4J266  A0A0B4J268  A0A0B4J271  A0A0B4J272  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J273  A0A0B4J274  A0A0B4J275  A0A0B4J276  A0A0B4J277  A0A0B4J279  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J280  A0A0B4J2A2  A0A0B4J2D5  A0A0B4J2D9  A0A0B4J2E0  A0A0B4J2F0  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0B4J2F2  A0A0B4J2H0  A0A0C4DH24  A0A0C4DH25  A0A0C4DH26  A0A0C4DH27  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0C4DH28  A0A0C4DH29  A0A0C4DH30  A0A0C4DH31  A0A0C4DH32  A0A0C4DH33  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0C4DH34  A0A0C4DH35  A0A0C4DH36  A0A0C4DH38  A0A0C4DH39  A0A0C4DH41  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0C4DH42  A0A0C4DH43  A0A0C4DH55  A0A0C4DH59  A0A0C4DH67  A0A0C4DH68  \
0    0.000909         0.0         0.0         0.0         0.0         0.0
1    0.001401         0.0         0.0         0.0         0.0         0.0
2    0.001467         0.0         0.0         0.0         0.0         0.0
3    0.001167         0.0         0.0         0.0         0.0         0.0
4    0.001144         0.0         0.0         0.0         0.0         0.0

   A0A0C4DH69  A0A0C4DH72  A0A0C4DH73  A0A0C5B5G6  A0A0D9SF12  A0A0G2JMD5  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0G2JMI3  A0A0G2JS06  A0A0J9YVY3  A0A0J9YWL9  A0A0J9YWX3  A0A0J9YX06  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0J9YX35  A0A0J9YX75  A0A0J9YX94  A0A0J9YXA8  A0A0J9YXM7  A0A0J9YXQ4  \
0    0.000000         0.0         0.0         0.0         0.0         0.0
1    0.001389         0.0         0.0         0.0         0.0         0.0
2    0.000000         0.0         0.0         0.0         0.0         0.0
3    0.000000         0.0         0.0         0.0         0.0         0.0
4    0.000000         0.0         0.0         0.0         0.0         0.0

   A0A0J9YXX1  A0A0J9YY54  A0A0K0K1A3  A0A0K0K1A5  A0A0K0K1B3  A0A0K0K1C0  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0K0K1C4  A0A0K0K1D8  A0A0K0K1E9  A0A0K0K1G6  A0A0K0K1G8  A0A0K2S4Q6  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0U1RQE8  A0A0U1RQF7  A0A0U1RQI7  A0A0U1RQS6  A0A0U1RR11  A0A0U1RR37  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0U1RRA0  A0A0U1RRE5  A0A0U1RRI6  A0A0U1RRK4  A0A0U1RRL7  A0A0U1RRN3  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A0X1KG70  A0A183  A0A1B0GTC6  A0A1B0GTD5  A0A1B0GTH6  A0A1B0GTI1  \
0         0.0     0.0         0.0         0.0         0.0         0.0
1         0.0     0.0         0.0         0.0         0.0         0.0
2         0.0     0.0         0.0         0.0         0.0         0.0
3         0.0     0.0         0.0         0.0         0.0         0.0
4         0.0     0.0         0.0         0.0         0.0         0.0

   A0A1B0GTI8  A0A1B0GTK4  A0A1B0GTL2  A0A1B0GTQ4  A0A1B0GTR0  A0A1B0GTR4  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A1B0GTS1  A0A1B0GTU1  A0A1B0GTU2  A0A1B0GTW7  A0A1B0GTY4  A0A1B0GTZ2  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A1B0GU29  A0A1B0GU33  A0A1B0GU71  A0A1B0GUA5  A0A1B0GUA6  A0A1B0GUA7  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A1B0GUA9  A0A1B0GUC4  A0A1B0GUI7  A0A1B0GUJ8  A0A1B0GUQ0  A0A1B0GUS0  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A1B0GUS4  A0A1B0GUT2  A0A1B0GUU1  A0A1B0GUV1  A0A1B0GUV7  A0A1B0GUW6  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A1B0GUW7  A0A1B0GUX0  A0A1B0GUY1  A0A1B0GV03  A0A1B0GV85  A0A1B0GV90  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   A0A1B0GVD1  A0A1B0GVG4  A0A1B0GVG6  A0A1B0GVH4  A0A1B0GVH6  A0A1B0GVH7  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0

In [ ]:
fields_to_annotate = [
    "organism", "tissue", "disease", "cell_part", "cell_line", "instrument", "fragmentation", "enzymes",
    "modifications", "collision_energy", "gradient_time_min", "lc_column", "acquisition", "labeling",
    "ionization", "treatment_type", "treatment_name", "treatment_class", "fractionation", "enrichment"
]

# Function for fetching SDRF

In [ ]:
SDRF_CACHE_DIR = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\run_level_data\sdrf_cache"
os.makedirs(SDRF_CACHE_DIR, exist_ok=True)


def fetch_sdrf(pxd_id: str, timeout: int = 240, use_cache: bool = True) -> pd.DataFrame | None:
    """Fetch SDRF table for a PXD accession from PRIDE.

    If use_cache is True, saves to / loads from local cache on first fetch.
    Returns a DataFrame if SDRF exists, None otherwise.
    """
    # Check local cache first
    cache_path = os.path.join(SDRF_CACHE_DIR, f"{pxd_id}.sdrf.tsv")
    if use_cache and os.path.exists(cache_path):
        return pd.read_csv(cache_path, sep="\t")

    # Find SDRF file in PRIDE file list
    url = f"https://www.ebi.ac.uk/pride/ws/archive/v3/projects/{pxd_id}/files"
    page = 0
    sdrf_file = None

    while page < 50:
        try:
            resp = requests.get(url, params={"pageSize": 100, "page": page}, timeout=30)
            resp.raise_for_status()
            files = resp.json()
            if not files:
                break
            for f in files:
                name = f.get("fileName", "")
                if name.lower() == "sdrf.tsv" or name.lower().endswith(".sdrf.tsv"):
                    sdrf_file = f
                    break
            if sdrf_file or len(files) < 100:
                break
            page += 1
        except Exception as e:
            print(f"  {pxd_id}: file list error: {e}")
            break

    if not sdrf_file:
        return None

    download_url = None
    for loc in sdrf_file.get("publicFileLocations", []):
        u = loc.get("value", "")
        if u.startswith("ftp://"):
            download_url = u.replace(
                "ftp://ftp.pride.ebi.ac.uk/pride/data/archive/",
                "https://ftp.pride.ebi.ac.uk/pride/data/archive/"
            )
            break
        elif u.startswith("http"):
            download_url = u
            break

    if not download_url:
        return None

    try:
        resp = requests.get(download_url, timeout=timeout)
        resp.raise_for_status()
        df = pd.read_csv(StringIO(resp.text), sep="\t")

        # Save to cache
        if use_cache:
            df.to_csv(cache_path, sep="\t", index=False)

        return df
    except Exception as e:
        print(f"  {pxd_id}: SDRF download failed: {e}")
        return None

In [ ]:
# Test: fetch SDRF for a known PXD
sdrf = fetch_sdrf("PXD008012")
if sdrf is not None:
    print(f"Rows: {len(sdrf)}, Columns: {len(sdrf.columns)}")
    print(f"\nColumn names:\n{list(sdrf.columns)}")
    display(sdrf.head(3))
else:
    print("No SDRF found")

Rows: 141, Columns: 37

Column names:
['Source Name', 'Characteristics[organism]', 'Characteristics[organism part]', 'Characteristics[age]', 'Characteristics[cell line]', 'Characteristics[cell type]', 'Characteristics[ancestry category]', 'Characteristics[developmental stage]', 'Characteristics[sex]', 'Characteristics[disease]', 'Characteristics[phenotype]', 'Characteristics[individual]', 'Characteristics[enrichment process]', 'assay name', 'comment[label]', 'comment[data file]', 'comment[file uri]', 'comment[fractionation method]', 'comment[technical replicate]', 'comment[fraction identifier]', 'comment[cleavage agent details]', 'comment[cleavage agent details].1', 'comment[ms2 mass analyzer]', 'comment[instrument]', 'comment[modification parameters]', 'comment[modification parameters].1', 'comment[modification parameters].2', 'comment[modification parameters].3', 'comment[dissociation method]', 'comment[collision energy]', 'comment[precursor mass tolerance]', 'comment[fragment mass tolerance]', 'Material Type', 'factor value[phenotype]', 'factor value[enrichment process]', 'sampleChecksum', 'sampleAccession']

,Source Name,Characteristics[organism],Characteristics[organism part],Characteristics[age],Characteristics[cell line],Characteristics[cell type],Characteristics[ancestry category],Characteristics[developmental stage],Characteristics[sex],Characteristics[disease],Characteristics[phenotype],Characteristics[individual],Characteristics[enrichment process],assay name,comment[label],comment[data file],comment[file uri],comment[fractionation method],comment[technical replicate],comment[fraction identifier],comment[cleavage agent details],comment[cleavage agent details].1,comment[ms2 mass analyzer],comment[instrument],comment[modification parameters],comment[modification parameters].1,comment[modification parameters].2,comment[modification parameters].3,comment[dissociation method],comment[collision energy],comment[precursor mass tolerance],comment[fragment mass tolerance],Material Type,factor value[phenotype],factor value[enrichment process],sampleChecksum,sampleAccession
0,PXD008012-Sample 1,Homo sapiens,breast,50Y,HCC38,Epithelial,Caucasian,adult,female,Triple-negative breast cancer,indolent,not applicable,enrichment of phosphorylated Protein,run 1,AC=MS:1002038;NT=label free sample,20131217_OR8_RP_HP_C1.raw,ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2...,not available,1,1,NT=Trypsin; AC=MS:1001251; CS=(?<=[KR])(?!P),NT=Lys-C;AC=MS:1001309,AC=MS:1000484; NT=Orbitrap,NT=LTQ Orbitrap Elite;AC=MS:1001910,NT=Carbamidomethyl;TA=C;MT=fixed;AC=UNIMOD:4,NT=Oxidation;MT=variable;TA=M;AC=UNIMOD:35,NT=Acetyl;AC=UNIMOD:1;PP=Protein N-term;MT=var...,"NT=Phospho;MT=variable;TA=S,T,Y;AC=UNIMOD:21",AC=MS:1000133;NT=CID,35% NCE,20 ppm,not available,cell line,indolent,enrichment of phosphorylated Protein,15bcc930cef29feb8d4d40375ee5953b7f2e01bf39a9f1...,SAMEA7715768
1,PXD008012-Sample 1,Homo sapiens,breast,50Y,HCC38,Epithelial,Caucasian,adult,female,Triple-negative breast cancer,indolent,not applicable,enrichment of phosphorylated Protein,run 2,AC=MS:1002038;NT=label free sample,20131217_OR8_RP_HP_C1_rr.raw,ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2...,not available,2,1,NT=Trypsin; AC=MS:1001251; CS=(?<=[KR])(?!P),NT=Lys-C;AC=MS:1001309,AC=MS:1000484; NT=Orbitrap,NT=LTQ Orbitrap Elite;AC=MS:1001910,NT=Carbamidomethyl;TA=C;MT=fixed;AC=UNIMOD:4,NT=Oxidation;MT=variable;TA=M;AC=UNIMOD:35,NT=Acetyl;AC=UNIMOD:1;PP=Protein N-term;MT=var...,"NT=Phospho;MT=variable;TA=S,T,Y;AC=UNIMOD:21",AC=MS:1000133;NT=CID,35% NCE,20 ppm,not available,cell line,indolent,enrichment of phosphorylated Protein,15bcc930cef29feb8d4d40375ee5953b7f2e01bf39a9f1...,SAMEA7715768
2,PXD008012-Sample 2,Homo sapiens,breast,50Y,HCC38,Epithelial,Caucasian,adult,female,Triple-negative breast cancer,indolent,not applicable,enrichment of phosphorylated Protein,run 3,AC=MS:1002038;NT=label free sample,20131217_OR8_RP_HP_C1b.raw,ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2...,not available,1,1,NT=Trypsin; AC=MS:1001251; CS=(?<=[KR])(?!P),NT=Lys-C;AC=MS:1001309,AC=MS:1000484; NT=Orbitrap,NT=LTQ Orbitrap Elite;AC=MS:1001910,NT=Carbamidomethyl;TA=C;MT=fixed;AC=UNIMOD:4,NT=Oxidation;MT=variable;TA=M;AC=UNIMOD:35,NT=Acetyl;AC=UNIMOD:1;PP=Protein N-term;MT=var...,"NT=Phospho;MT=variable;TA=S,T,Y;AC=UNIMOD:21",AC=MS:1000133;NT=CID,35% NCE,20 ppm,not available,cell line,indolent,enrichment of phosphorylated Protein,ca1ae2dce5816cc772fcb19a3751cbb42378c450bc4aae...,SAMEA7715769

In [ ]:
# Check what run names look like in the parquet data vs SDRF data files
print("=== Run names in DDA data (first 5) ===")
print(dda_data.columns[:5].tolist())
print()

print("=== SDRF comment[data file] (first 5) ===")
print(sdrf["comment[data file]"].head().tolist())

=== Run names in DDA data (first 5) ===
['pxd', 'run', 'A0A024RBG1', 'A0A075B6H7', 'A0A075B6H8']

=== SDRF comment[data file] (first 5) ===
['20131217_OR8_RP_HP_C1.raw', '20131217_OR8_RP_HP_C1_rr.raw', '20131217_OR8_RP_HP_C1b.raw', '20131217_OR8_RP_HP_C1b_rr.raw', '20131217_OR8_RP_HP_C3.raw']

# SDRF -> Run-level metadata extraction

In [ ]:
import re, os

# --- SDRF column -> metadata field mapping ---
SDRF_COL_MAP = {
    "characteristics[organism]":       "organism",
    "characteristics[organism part]":  "tissue",
    "characteristics[disease]":        "disease",
    "characteristics[cell line]":      "cell_line",
    "comment[instrument]":             "instrument",
    "comment[dissociation method]":    "fragmentation",
    "comment[collision energy]":       "collision_energy",
    "comment[cleavage agent details]": "enzymes",
    "comment[modification parameters]":"modifications",
    "comment[label]":                  "labeling",
    "characteristics[enrichment process]": "enrichment",
}

# Load known organisms for organism/tissue swap detection
_ORGANISMS_PATH = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\ontologies\organisms.txt"
KNOWN_ORGANISMS = set()
with open(_ORGANISMS_PATH, encoding="utf-8") as _f:
    for _line in _f:
        t = _line.strip()
        if t and not t.startswith("#"):
            KNOWN_ORGANISMS.add(t.lower())


def _parse_sdrf_value(val) -> str | None:
    """Extract the NT= (name) portion from an SDRF ontology-annotated value."""
    if pd.isna(val):
        return None
    val = str(val).strip()
    if not val or val.lower() in ("not available", "not applicable"):
        return None
    m = re.search(r"NT=([^;]+)", val)
    if m:
        return m.group(1).strip()
    return val


def _stem_filename(name: str) -> str:
    """Strip common raw-file extensions to get a comparable run stem."""
    return re.sub(r"\.(raw|mzML|d|wiff)$", "", name, flags=re.IGNORECASE)


def _normalize_sdrf_columns(sdrf: pd.DataFrame) -> dict:
    """Build a lowercase column-name -> original column-name lookup."""
    return {c.lower(): c for c in sdrf.columns}


def _find_duplicate_columns(sdrf: pd.DataFrame, sdrf_key: str) -> list[str]:
    """Find the base column + any pandas-suffixed duplicates (.1, .2, ...)."""
    return [c for c in sdrf.columns if c.lower() == sdrf_key or re.match(rf"^{re.escape(sdrf_key)}\.\d+$", c.lower())]


def _fix_organism_tissue_swap(df: pd.DataFrame) -> pd.DataFrame:
    """Fix cases where SDRF has organism and tissue columns swapped."""
    if "organism" not in df.columns or "tissue" not in df.columns:
        return df
    df = df.copy()
    tissue_is_organism = df["tissue"].apply(
        lambda v: v.lower() in KNOWN_ORGANISMS if pd.notna(v) else False
    )
    organism_is_missing = df["organism"].isna()
    swap_mask = tissue_is_organism & organism_is_missing
    if swap_mask.any():
        df.loc[swap_mask, "organism"] = df.loc[swap_mask, "tissue"]
        df.loc[swap_mask, "tissue"] = None
        print(f"  Fixed organism/tissue swap for {swap_mask.sum()} rows")
    return df


def _fill_enrichment_fallback(df: pd.DataFrame, sdrf: pd.DataFrame, col_lookup: dict) -> pd.DataFrame:
    """Fill enrichment from factor value[enrichment process] if characteristics was empty."""
    fv_col = col_lookup.get("factor value[enrichment process]")
    if fv_col is None or "enrichment" not in df.columns:
        return df
    df = df.copy()
    for idx in df.index:
        if pd.isna(df.at[idx, "enrichment"]) and idx < len(sdrf):
            fv = sdrf.iloc[idx][fv_col]
            if pd.notna(fv) and str(fv).strip().lower() not in ("not available", "not applicable", ""):
                df.at[idx, "enrichment"] = str(fv).strip()
    return df


def _normalize_enrichment(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize enrichment: if value contains 'phospho', set to 'phosphorylation'."""
    if "enrichment" not in df.columns:
        return df
    df = df.copy()
    df["enrichment"] = df["enrichment"].apply(
        lambda v: "phosphorylation" if pd.notna(v) and "phospho" in v.lower() else v
    )
    return df


def _detect_fractionation(sdrf: pd.DataFrame, col_lookup: dict) -> bool:
    """Detect if the experiment uses fractionation from SDRF columns.

    Returns True if:
      - comment[fraction identifier] has more than 1 unique value, OR
      - comment[fractionation method] has a real value (not 'not available')
    """
    frac_id_col = col_lookup.get("comment[fraction identifier]")
    if frac_id_col is not None:
        unique_ids = sdrf[frac_id_col].dropna().unique()
        if len(unique_ids) > 1:
            return True

    frac_method_col = col_lookup.get("comment[fractionation method]")
    if frac_method_col is not None:
        methods = sdrf[frac_method_col].dropna().unique()
        real_methods = [m for m in methods if str(m).strip().lower() not in ("not available", "not applicable", "")]
        if real_methods:
            return True

    return False


def sdrf_to_run_metadata(sdrf: pd.DataFrame, pxd_id: str) -> pd.DataFrame:
    """Convert an SDRF table into per-run metadata rows."""
    col_lookup = _normalize_sdrf_columns(sdrf)
    data_file_col = col_lookup.get("comment[data file]")
    if data_file_col is None:
        raise ValueError("SDRF has no 'comment[data file]' column")

    rows = []
    for _, srow in sdrf.iterrows():
        run_name = _stem_filename(str(srow[data_file_col]))
        row = {"pxd": pxd_id, "run": run_name}
        for sdrf_key, meta_field in SDRF_COL_MAP.items():
            orig_col = col_lookup.get(sdrf_key)
            if orig_col is None:
                row[meta_field] = None
                continue
            dup_cols = _find_duplicate_columns(sdrf, sdrf_key)
            if not dup_cols:
                dup_cols = [orig_col]
            parsed_vals = []
            for dc in dup_cols:
                v = _parse_sdrf_value(srow[dc])
                if v and v not in parsed_vals:
                    parsed_vals.append(v)
            row[meta_field] = "; ".join(parsed_vals) if parsed_vals else None
        # Fraction identifier (raw value, not parsed through NT=)
        frac_col = col_lookup.get("comment[fraction identifier]")
        if frac_col is not None:
            frac_val = srow.get(frac_col)
            row["fraction_identifier"] = int(frac_val) if pd.notna(frac_val) else None
        else:
            row["fraction_identifier"] = None

        rows.append(row)

    df = pd.DataFrame(rows)
    df = _fix_organism_tissue_swap(df)
    df = _fill_enrichment_fallback(df, sdrf, col_lookup)
    df = _normalize_enrichment(df)

    # Fractionation: project-level boolean
    is_fractionated = _detect_fractionation(sdrf, col_lookup)
    df["fractionation"] = True if is_fractionated else None

    return df


# --- Test with PXD008012 ---
run_meta = sdrf_to_run_metadata(sdrf, "PXD008012")
print(f"Run-level metadata: {len(run_meta)} rows, {len(run_meta.columns)} columns")
display(run_meta.head(10))

Run-level metadata: 141 rows, 15 columns

,pxd,run,organism,tissue,disease,cell_line,instrument,fragmentation,collision_energy,enzymes,modifications,labeling,enrichment,fraction_identifier,fractionation
0,PXD008012,20131217_OR8_RP_HP_C1,Homo sapiens,breast,Triple-negative breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
1,PXD008012,20131217_OR8_RP_HP_C1_rr,Homo sapiens,breast,Triple-negative breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
2,PXD008012,20131217_OR8_RP_HP_C1b,Homo sapiens,breast,Triple-negative breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
3,PXD008012,20131217_OR8_RP_HP_C1b_rr,Homo sapiens,breast,Triple-negative breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
4,PXD008012,20131217_OR8_RP_HP_C3,Homo sapiens,breast,Triple-negative breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
5,PXD008012,20131217_OR8_RP_HP_C3_rr,Homo sapiens,breast,Triple-negative breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
6,PXD008012,20131217_OR8_RP_HP_C3b,Homo sapiens,breast,Triple-negative breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
7,PXD008012,20131217_OR8_RP_HP_C3b_rr,Homo sapiens,breast,Triple-negative breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
8,PXD008012,20131217_OR8_RP_HP_C3c,Homo sapiens,breast,Triple-negative breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None
9,PXD008012,20131217_OR8_RP_HP_C3c_rr,Homo sapiens,breast,Triple-negative breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,Trypsin; Lys-C,Carbamidomethyl; Oxidation; Acetyl; Phospho,label free sample,phosphorylation,1,None

# Normalize SDRF metadata through the normalization pipeline
Same SapBERT + post-normalization map used for the LLM extraction output.

In [ ]:
import sys, importlib

PROJECT_ROOT = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata"
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import normalization.normalize_extraction
importlib.reload(normalization.normalize_extraction)

from normalization.config import NormalizationConfig
from normalization.normalizer import TermNormalizer
from normalization.normalize_extraction import (
    CellLineExactMatcher, EVIDENCE_ARRAY_FIELDS,
    _load_post_normalization_map, _apply_post_normalization,
)

norm_config = NormalizationConfig.from_dict({
    "ontology_dir": os.path.join(PROJECT_ROOT, "ontologies"),
    "cache_dir": os.path.join(PROJECT_ROOT, "ontology_cache"),
    "use_gpu": True,
})
normalizer = TermNormalizer(norm_config)
normalizer.load_all_ontologies()

cell_line_path = norm_config.get_ontology_path("cell_lines")
cell_line_matcher = CellLineExactMatcher(cell_line_path) if cell_line_path and cell_line_path.exists() else None

post_map = _load_post_normalization_map(norm_config.ontology_dir)

print(f"Loaded {len(normalizer.indices)} ontologies")
print(f"Post-normalization map: {post_map}")
if cell_line_matcher:
    print(f"Cell line matcher: {len(cell_line_matcher.canonical)} entries")

2026-04-10 17:31:29,873 - INFO - Embedding ontologies with SapBERT for FAISS:
2026-04-10 17:31:29,910 - INFO -   Organisms                        81 terms (cached)
2026-04-10 17:31:29,919 - INFO -   Tissues                         107 terms (cached)
2026-04-10 17:31:29,932 - INFO -   Diseases                        129 terms (cached)
2026-04-10 17:31:29,943 - INFO -   Cell Parts                       13 terms (cached)
2026-04-10 17:31:29,951 - INFO -   Cell Lines                      117 terms (cached)
2026-04-10 17:31:29,960 - INFO -   Instruments                      36 terms (cached)
2026-04-10 17:31:29,975 - INFO -   Fragmentation                     5 terms (cached)
2026-04-10 17:31:29,982 - INFO -   Acquisition                       2 terms (cached)
2026-04-10 17:31:29,992 - INFO -   Ionization                        4 terms (cached)
2026-04-10 17:31:30,004 - INFO -   Labeling                          4 terms (cached)
2026-04-10 17:31:30,016 - INFO -   Modifications                    18 terms (cached)
2026-04-10 17:31:30,026 - INFO -   Enzymes                           7 terms (cached)
2026-04-10 17:31:30,038 - INFO -   LC Column                         5 terms (cached)
2026-04-10 17:31:30,049 - INFO -   Treatments                        3 terms (cached)

Loaded 14 ontologies
Post-normalization map: {'disease': {'triple negative breast cancer': 'breast cancer', 'disease free': 'healthy'}}
Cell line matcher: 113 entries

In [ ]:
# Fields from SDRF_COL_MAP that have a corresponding SapBERT ontology
NORMALIZABLE_FIELDS = {
    field: entity_type
    for field, entity_type in EVIDENCE_ARRAY_FIELDS.items()
    if field in SDRF_COL_MAP.values()
}

# Fields where unmatched values should be dropped (set to None).
# These must match controlled vocabulary; unknown values are not useful.
STRICT_FIELDS = {"organism", "tissue", "disease", "instrument", "fragmentation", "enzymes"}

def normalize_run_metadata(df: pd.DataFrame, normalizer: TermNormalizer,
                           cell_line_matcher: CellLineExactMatcher,
                           post_map: dict) -> pd.DataFrame:
    """Normalize SDRF-derived run metadata through the same pipeline as LLM extractions.

    For multi-value fields (e.g. "Trypsin; Lys-C"), each value is normalized individually.
    Duplicate values after normalization are removed.
    For strict fields, unmatched values are dropped.
    """
    df = df.copy()

    for field, entity_type in NORMALIZABLE_FIELDS.items():
        if field not in df.columns:
            continue
        strict = field in STRICT_FIELDS
        normalized = []
        for val in df[field]:
            if pd.isna(val):
                normalized.append(None)
                continue
            parts = [v.strip() for v in str(val).split(";")]
            norm_parts = []
            seen = set()
            for part in parts:
                if not part:
                    continue
                result = normalizer.normalize(part, entity_type=entity_type)
                if result.is_normalized:
                    item = {"ontology_name": result.ontology_name}
                    _apply_post_normalization(item, entity_type, post_map)
                    out = item["ontology_name"]
                else:
                    if strict:
                        continue
                    out = part
                if out.lower() not in seen:
                    norm_parts.append(out)
                    seen.add(out.lower())
            normalized.append("; ".join(norm_parts) if norm_parts else None)
        df[field] = normalized

    # Cell line exact matching
    if cell_line_matcher and "cell_line" in df.columns:
        df["cell_line"] = df["cell_line"].apply(
            lambda v: cell_line_matcher.match(v) or v if pd.notna(v) else None
        )

    return df


run_meta_normalized = normalize_run_metadata(run_meta, normalizer, cell_line_matcher, post_map)

# Show disease normalization changes
comparison = pd.DataFrame({
    "before": run_meta["disease"],
    "after": run_meta_normalized["disease"],
})
changed = comparison[comparison["before"] != comparison["after"]].drop_duplicates()
print("Disease normalization changes:")
display(changed if len(changed) else "No changes")

display(run_meta_normalized.head(5))

c:\Users\sander\miniconda3\envs\agentic-metadata\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-04-10 17:31:34,755 - INFO - HTTP Request: HEAD https://huggingface.co/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-10 17:31:34,763 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/090663c3ae57bf35ffe4d0d468a2a88d03051a4d/config.json "HTTP/1.1 200 OK"
2026-04-10 17:31:34,867 - INFO - HTTP Request: HEAD https://huggingface.co/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-10 17:31:34,875 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/090663c3ae57bf35ffe4d0d468a2a88d03051a4d/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-10 17:31:35,009 - INFO - HTTP Request: GET https://huggingface.co/api/models/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-10 17:31:35,121 - INFO - HTTP Request: GET https://huggingface.co/api/models/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-10 17:31:35,237 - INFO - HTTP Request: HEAD https://huggingface.co/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-10 17:31:35,245 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cambridgeltl/SapBERT-from-PubMedBERT-fulltext/090663c3ae57bf35ffe4d0d468a2a88d03051a4d/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 17922.07it/s]
2026-04-10 17:31:35,360 - INFO - SapBERT model loaded (GPU)

Disease normalization changes:

                          before          after
0  Triple-negative breast cancer  breast cancer

,pxd,run,organism,tissue,disease,cell_line,instrument,fragmentation,collision_energy,enzymes,modifications,labeling,enrichment,fraction_identifier,fractionation
0,PXD008012,20131217_OR8_RP_HP_C1,Homo sapiens,breast,breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1,None
1,PXD008012,20131217_OR8_RP_HP_C1_rr,Homo sapiens,breast,breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1,None
2,PXD008012,20131217_OR8_RP_HP_C1b,Homo sapiens,breast,breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1,None
3,PXD008012,20131217_OR8_RP_HP_C1b_rr,Homo sapiens,breast,breast cancer,HCC38,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1,None
4,PXD008012,20131217_OR8_RP_HP_C3,Homo sapiens,breast,breast cancer,MDA-MB-231,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1,None

In [ ]:
# Match normalized SDRF metadata against actual runs in the parquet data
pxd_runs = dda_data[dda_data["pxd"] == "PXD008012"][["pxd", "run"]].copy()
merged = pxd_runs.merge(run_meta_normalized, on=["pxd", "run"], how="left")

matched = merged[merged["organism"].notna()]
unmatched = merged[merged["organism"].isna()]
print(f"Total runs in parquet: {len(pxd_runs)}")
print(f"Matched to SDRF:      {len(matched)}")
print(f"Unmatched:            {len(unmatched)}")

if len(unmatched):
    print(f"\nUnmatched run names:\n{unmatched['run'].tolist()}")

display(merged.head(10))

Total runs in parquet: 118
Matched to SDRF:      117
Unmatched:            1

Unmatched run names:
['20131217_OR8_RP_HP_C2b']

,pxd,run,organism,tissue,disease,cell_line,instrument,fragmentation,collision_energy,enzymes,modifications,labeling,enrichment,fraction_identifier,fractionation
0,PXD008012,20131217_OR8_RP_HP_C8_rr,Homo sapiens,breast,breast cancer,MDA-MB-157,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
1,PXD008012,20140113_OR8_RP_HP_B20A_rr,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
2,PXD008012,20140113_OR8_RP_HP_B4A_rr,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
3,PXD008012,20131217_OR8_RP_HP_C6b,Homo sapiens,breast,breast cancer,MDA-MB-415,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
4,PXD008012,20140108_OR8_RP_HP_B6A,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
5,PXD008012,20140113_OR8_RP_HP_B10B,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
6,PXD008012,20140113_OR8_RP_HP_B19C_rr,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
7,PXD008012,20140113_OR8_RP_HP_B21A_rr,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
8,PXD008012,20140113_OR8_RP_HP_B18B_rr,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None
9,PXD008012,20140113_OR8_RP_HP_B39A_rr,Homo sapiens,breast,breast cancer,NaN,LTQ Orbitrap Elite,CID,35% NCE,trypsin; LysC,C-carbamidomethylation; M-oxidation; Acetyl; P...,label-free,phosphorylation,1.0,None

# Multi-project SDRF extraction
Fetch SDRFs for a batch of projects, parse to run-level metadata, normalize, and combine.

In [ ]:
import time, json as _json

# Find projects that have SDRFs from local metadata
meta_dir = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\results\manuscripts\metadata"
sdrf_pxds = []
for fname in sorted(os.listdir(meta_dir)):
    with open(os.path.join(meta_dir, fname)) as fh:
        data = _json.load(fh)
    if data.get("has_sdrf"):
        sdrf_pxds.append(fname.replace(".meta.json", ""))

print(f"Projects with SDRF: {len(sdrf_pxds)}")
print(f"Loading SDRFs (cached or from PRIDE)...")

sdrf_results = {}
for i, pxd_id in enumerate(sdrf_pxds):
    cache_path = os.path.join(SDRF_CACHE_DIR, f"{pxd_id}.sdrf.tsv")
    from_cache = os.path.exists(cache_path)
    sdrf_df = fetch_sdrf(pxd_id)
    if sdrf_df is not None:
        sdrf_results[pxd_id] = sdrf_df
        src = "cache" if from_cache else "PRIDE"
        print(f"  [{i+1}/{len(sdrf_pxds)}] {pxd_id}: {len(sdrf_df)} rows ({src})")
    else:
        print(f"  [{i+1}/{len(sdrf_pxds)}] {pxd_id}: fetch failed")
    if not from_cache:
        time.sleep(2)

print(f"\nSuccessfully loaded: {len(sdrf_results)}/{len(sdrf_pxds)}")

Projects with SDRF: 65
Loading SDRFs (cached or from PRIDE)...
  [1/65] PXD000396: 40 rows (cache)
  [2/65] PXD000561: 2212 rows (cache)
  [3/65] PXD001325: 48 rows (cache)
  [4/65] PXD001474: 27 rows (cache)
  [5/65] PXD001725: 30 rows (cache)
  [6/65] PXD002088: 150 rows (cache)
  [7/65] PXD002255: 428 rows (cache)
  [8/65] PXD003531: 59 rows (cache)
  [9/65] PXD003668: 101 rows (cache)
  [10/65] PXD004143: 4 rows (cache)
  [11/65] PXD004332: 61 rows (cache)
  [12/65] PXD004624: 6 rows (cache)
  [13/65] PXD004683: 192 rows (cache)
  [14/65] PXD005354: 1560 rows (cache)
  [15/65] PXD005507: 18 rows (cache)
  [16/65] PXD005940: 216 rows (cache)
  [17/65] PXD006233: 378 rows (cache)
  [18/65] PXD006401: 28 rows (cache)
  [19/65] PXD006607: 1028 rows (cache)
  [20/65] PXD006675: 610 rows (cache)
  [21/65] PXD006833: 199 rows (cache)
  [22/65] PXD006914: 24 rows (cache)
  [23/65] PXD007160: 1687 rows (cache)
  [24/65] PXD008012: 141 rows (cache)
  [25/65] PXD008222: 456 rows (cache)
  [26/65] PXD008722: 252 rows (cache)
  [27/65] PXD008934: 34 rows (cache)
  [28/65] PXD010154: 1800 rows (cache)
  [29/65] PXD010698: 5 rows (cache)
  [30/65] PXD010705: 3 rows (cache)
  [31/65] PXD010708: 15 rows (cache)
  [32/65] PXD011175: 28 rows (cache)
  [33/65] PXD011839: 399 rows (cache)
  [34/65] PXD012755: 32 rows (cache)
  [35/65] PXD013523: 198 rows (cache)
  [36/65] PXD013868: 1560 rows (cache)
  [37/65] PXD013923: 372 rows (cache)
  [38/65] PXD015957: 30 rows (cache)
  [39/65] PXD018682: 2 rows (cache)
  [40/65] PXD020192: 92 rows (cache)
  [41/65] PXD036886: 108 rows (cache)
  [42/65] PXD041899: 34 rows (cache)
  [43/65] PXD048836: 10 rows (cache)
  [44/65] PXD048839: 10 rows (cache)
  [45/65] PXD048840: 10 rows (cache)
  [46/65] PXD051889: 16 rows (cache)
  [47/65] PXD053783: 40 rows (cache)
  [48/65] PXD056077: 72 rows (cache)
  [49/65] PXD056281: 81 rows (cache)
  [50/65] PXD056559: 70 rows (cache)
  [51/65] PXD057347: 11 rows (cache)
  [52/65] PXD058727: 30 rows (cache)
  [53/65] PXD059390: 28 rows (cache)
  [54/65] PXD059416: 28 rows (cache)
  [55/65] PXD059419: 42 rows (cache)
  [56/65] PXD059428: 56 rows (cache)
  [57/65] PXD059544: 24 rows (cache)
  [58/65] PXD060764: 30 rows (cache)
  [59/65] PXD061667: 3 rows (cache)
  [60/65] PXD063253: 589 rows (cache)
  [61/65] PXD063553: 208 rows (cache)
  [62/65] PXD063595: 8 rows (cache)
  [63/65] PXD066622: 24 rows (cache)
  PXD067153: SDRF download failed: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  [64/65] PXD067153: fetch failed
  PXD067220: SDRF download failed: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

  [65/65] PXD067220: fetch failed

Successfully loaded: 63/65

In [ ]:
# Parse all SDRFs to run-level metadata
all_run_meta = []
for pxd_id, sdrf_df in sdrf_results.items():
    try:
        rm = sdrf_to_run_metadata(sdrf_df, pxd_id)
        all_run_meta.append(rm)
        print(f"  {pxd_id}: {len(rm)} runs extracted")
    except Exception as e:
        print(f"  {pxd_id}: FAILED - {e}")

run_meta_all = pd.concat(all_run_meta, ignore_index=True) if all_run_meta else pd.DataFrame()
print(f"\nTotal run-level rows: {len(run_meta_all)}")
print(f"Projects with data: {run_meta_all['pxd'].nunique()}")
display(run_meta_all.head(10))

  PXD000396: 40 runs extracted
  PXD000561: 2212 runs extracted
  PXD001325: 48 runs extracted
  PXD001474: 27 runs extracted
  PXD001725: 30 runs extracted
  PXD002088: 150 runs extracted
  PXD002255: 428 runs extracted
  PXD003531: 59 runs extracted
  PXD003668: FAILED - invalid literal for int() with base 10: 'not applicable'
  PXD004143: 4 runs extracted
  PXD004332: 61 runs extracted
  PXD004624: 6 runs extracted
  PXD004683: 192 runs extracted
  PXD005354: 1560 runs extracted
  PXD005507: 18 runs extracted
  PXD005940: 216 runs extracted
  PXD006233: 378 runs extracted
  PXD006401: 28 runs extracted
  PXD006607: 1028 runs extracted
  PXD006675: 610 runs extracted
  PXD006833: 199 runs extracted
  PXD006914: 24 runs extracted
  PXD007160: FAILED - invalid literal for int() with base 10: '19b'
  PXD008012: 141 runs extracted
  PXD008222: 456 runs extracted
  PXD008722: 252 runs extracted
  PXD008934: 34 runs extracted
  PXD010154: 1800 runs extracted
  PXD010698: 5 runs extracted
  PXD010705: 3 runs extracted
  PXD010708: FAILED - invalid literal for int() with base 10: 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2018/09/PXD010708/QEXI21818_F15.raw'
  PXD011175: 28 runs extracted
  PXD011839: 399 runs extracted
  PXD012755: 32 runs extracted
  PXD013523: 198 runs extracted
  PXD013868: 1560 runs extracted
  PXD013923: 372 runs extracted
  PXD015957: 30 runs extracted
  PXD018682: 2 runs extracted
  PXD020192: 92 runs extracted
  PXD036886: 108 runs extracted
  PXD041899: FAILED - invalid literal for int() with base 10: 'not applicable'
  PXD048836: 10 runs extracted
  PXD048839: 10 runs extracted
  PXD048840: 10 runs extracted
  PXD051889: 16 runs extracted
  PXD053783: 40 runs extracted
  PXD056077: 72 runs extracted
  PXD056281: 81 runs extracted
  PXD056559: 70 runs extracted
  PXD057347: 11 runs extracted
  PXD058727: 30 runs extracted
  PXD059390: FAILED - invalid literal for int() with base 10: 'not applicable'
  PXD059416: 28 runs extracted
  PXD059419: FAILED - invalid literal for int() with base 10: 'not applicable'
  PXD059428: 56 runs extracted
  PXD059544: 24 runs extracted
  PXD060764: 30 runs extracted
  PXD061667: 3 runs extracted
  PXD063253: 589 runs extracted
  PXD063553: 208 runs extracted
  PXD063595: 8 runs extracted
  Fixed organism/tissue swap for 24 rows
  PXD066622: 24 runs extracted

Total run-level rows: 14150
Projects with data: 57

,pxd,run,organism,tissue,disease,cell_line,instrument,fragmentation,collision_energy,enzymes,modifications,labeling,enrichment,fraction_identifier,fractionation
0,PXD000396,120315QEx2_RS1_50nl-min_10ngHeLa_1h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
1,PXD000396,120327QEx2_RS1_50nl-min_0k1HeLa_14h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
2,PXD000396,120323QEx2_RS1_20nl-min_0k1HeLa_10h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
3,PXD000396,120315QEx2_RS1_50nl-min_10ngHeLa_1h_02,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
4,PXD000396,120323QEx2_RS1_20nl-min_0k1HeLa_5h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
5,PXD000396,120323QEx2_RS1_20nl-min_0k1HeLa_3h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
6,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_8h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
7,PXD000396,120330QEx2_RS1_50nl-min_100ngHeLa_14h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
8,PXD000396,120315QEx2_RS1_50nl-min_10ngHeLa_5h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True
9,PXD000396,120309QEx2_RS1_50nl-min_0k1HeLa_3h_01,Homo sapiens,None,epithelial cervix carcinoma,HeLa,Q Exactive,None,None,Trypsin,Carbamidomethyl; Oxidation; Deamidated,label free sample,None,1,True

# normalize the vocabulary

In [ ]:
# Normalize all run metadata through the pipeline
run_meta_all_normalized = normalize_run_metadata(
    run_meta_all, normalizer, cell_line_matcher, post_map
)

print(f"Normalized {len(run_meta_all_normalized)} rows across {run_meta_all_normalized['pxd'].nunique()} projects")

# Show a summary of unique values per field
for col in run_meta_all_normalized.columns:
    if col in ("pxd", "run"):
        continue
    unique_vals = run_meta_all_normalized[col].dropna().unique()
    print(f"\n{col}: {len(unique_vals)} unique values")
    if len(unique_vals) <= 15:
        for v in sorted(unique_vals):
            print(f"  - {v}")

display(run_meta_all_normalized.head(20))

Normalized 14150 rows across 57 projects

organism: 3 unique values
  - Arabidopsis thaliana
  - Homo sapiens
  - Mus musculus

tissue: 64 unique values

disease: 31 unique values

cell_line: 50 unique values

instrument: 12 unique values
  - LTQ Orbitrap Elite
  - LTQ Orbitrap Velos
  - Orbitrap Astral
  - Orbitrap Eclipse
  - Orbitrap Exploris 480
  - Orbitrap Fusion
  - Orbitrap Fusion Lumos
  - Q Exactive
  - Q Exactive HF
  - Q Exactive HF-X
  - Q Exactive Plus
  - Q Exactive; Q Exactive HF-X

fragmentation: 5 unique values
  - CID
  - CID; HCD
  - EThcD
  - HCD
  - HCD; CID

collision_energy: 13 unique values
  - 25 eV;27.5eV;30eV
  - 25% CE
  - 25% NCE
  - 27 eV
  - 27,32 NCE
  - 28% NCE
  - 30 NCE
  - 30% NCE
  - 35 NCE
  - 35% NCE
  - 40% NCE
  - 60-100 ms
  - NCE 28

enzymes: 7 unique values
  - ArgC
  - AspN
  - LysC
  - LysC; trypsin
  - chymotrypsin
  - trypsin
  - trypsin; LysC

modifications: 32 unique values

labeling: 15 unique values
  - SILAC
  - TMT
  - TMT127c
  - TMT128
  - TMT128c
  - TMT128n
  - TMT129
  - TMT129c
  - TMT129n
  - TMT130c
  - TMT130n
  - TMT132c
  - TMT132n
  - TMT134n
  - label-free

enrichment: 7 unique values
  - enrichment of low molecular weight Protein
  - enrichment of mRNA binding protein
  - enrichment of membrane protein
  - enrichment of nuclear extracts protein
  - enrichment of ubiquitinated protein
  - no enrichment
  - phosphorylation

fraction_identifier: 378 unique values

fractionation: 1 unique values
  - True

,pxd,run,organism,tissue,disease,cell_line,instrument,fragmentation,collision_energy,enzymes,modifications,labeling,enrichment,fraction_identifier,fractionation
0,PXD000396,120315QEx2_RS1_50nl-min_10ngHeLa_1h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
1,PXD000396,120327QEx2_RS1_50nl-min_0k1HeLa_14h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
2,PXD000396,120323QEx2_RS1_20nl-min_0k1HeLa_10h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
3,PXD000396,120315QEx2_RS1_50nl-min_10ngHeLa_1h_02,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
4,PXD000396,120323QEx2_RS1_20nl-min_0k1HeLa_5h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
5,PXD000396,120323QEx2_RS1_20nl-min_0k1HeLa_3h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
6,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_8h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
7,PXD000396,120330QEx2_RS1_50nl-min_100ngHeLa_14h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
8,PXD000396,120315QEx2_RS1_50nl-min_10ngHeLa_5h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
9,PXD000396,120309QEx2_RS1_50nl-min_0k1HeLa_3h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
10,PXD000396,120309QEx2_RS1_50nl-min_0k1HeLa_8h_02,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
11,PXD000396,120327QEx2_RS1_50nl-min_0k1HeLa_5h_02,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
12,PXD000396,120327QEx2_RS1_50nl-min_0k1HeLa_10h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
13,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_5h_02,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
14,PXD000396,120309QEx2_RS1_50nl-min_0k1HeLa_8h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
15,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_5h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
16,PXD000396,120327QEx2_RS1_50nl-min_0k1HeLa_1h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
17,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_1h_02,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
18,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_8h_02,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True
19,PXD000396,120315QEx2_RS1_20nl-min_10HeLa_1h_01,Homo sapiens,NaN,cervix carcinoma,HeLa,Q Exactive,NaN,None,trypsin,C-carbamidomethylation; M-oxidation; N-deamida...,label-free,None,1,True

In [ ]:
# save to C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\notebooks\run_metadata_sdrf.tsv
output_path = r"C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\notebooks\run_metadata_sdrf.tsv"

run_meta_all_normalized.to_csv(output_path, sep="\t", index=False)
print(f"\nSaved normalized run metadata to:\n{output_path}")

Saved normalized run metadata to:
C:\Users\sander\OneDrive\Bureaublad\Projects\agentic-metadata\notebooks\run_metadata_sdrf.tsv